__title__ = 'spacy-cld'
__version__ = '0.1.0'
__summary__ = 'spaCy pipeline component for guessing the language of Doc and Span objects.'
__url__ = 'https://github.com/nickdavidhaynes/spacy-cld'
__author__ = 'Nick Haynes'
__email__ = 'nickdavidhaynes@gmail.com'
__license__ = 'MIT'
